require:
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'

Metrics/MethodLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Lambda:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/CaseIndentation:
  IndentOneStep: true
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
