# this is our development docker-compose building on top of the production docker-compose, just mounting
# the sync image - not redefining anything else

version: '3'

services:
  myapp:
    volumes:
      - app-native-osx-sync:/app:nocopy # nocopy is important

# that the important thing
volumes:
  app-native-osx-sync:
    external: true
